kind = "AppSpec"
last_version = "0.0"
roles = [101, 100]
runtime_images = ["sysinner/innerstack-g3:el8"]
type_tags = ["enterprise", "net"]

[meta]
  id = "hooto-press-pgsql-x1"
  name = "Hooto Press CMS"
  version = "1.0"
  subtitle = "Hooto Press 内容管理系统"

[[depends]]
  id = "sysinner-pgsql-x1"
  name = "PostgreSQL x1"
  version = "1.0"

[[packages]]
  name = "hooto-press"
  version = "0.7"

[[packages]]
  name = "hooto-press-search"
  version = "1.0"
  release = "1"
  dist = "el8"
  arch = "x64"

[[executors]]
  name = "main"
  updated = 0
  exec_start = """DAEMON=/opt/hooto/press/bin/hooto-press
DAEMON_ARGS=\"-log_dir=/opt/hooto/press/var/log -minloglevel=1 -logtolevels=true\"
NAME=hooto-press

if pidof $NAME; then
    exit 0
fi

mkdir -p /opt/hooto/press/
rsync -av {{.inpack_prefix_hooto_press}}/* /opt/hooto/press/

$DAEMON $DAEMON_ARGS >> /home/action/var/log/hooto-press.log 2>&1 &
"""

  exec_stop = "killall hooto-press"
  priority = 8
  [executors.plan]
    on_tick = 60

[[service_ports]]
  name = "http"
  box_port = 9533

[configurator]
  name = "cfg/hooto-press"

  [[configurator.fields]]
    name = "iam_service_url"
    title = "IAM Service URL"
    type = 1
    default = "{{.xcs_sysinner_iam_service_url}}"

  [[configurator.fields]]
    name = "iam_service_url_frontend"
    title = "IAM Service URL for Frontend"
    type = 1
    default = "{{.xcs_sysinner_iam_service_url_frontend}}"

[exp_res]
  cpu_min = 2
  mem_min = 128
  vol_min = 1

[exp_deploy]
  rep_min = 1
  rep_max = 1
  sys_state = 1
  failover_time = 300
  failover_num_max = 0
  failover_rate_max = 0
  network_mode = 1
