# app_spec.toml - Application Specification v2 for hooto-press

name = "hooto-press"
description = "Hooto Press Content Management System"
image = "sysinner/innerstack-alpine:3.23"
version = "1.0.0"

[resources]
cpu_min = "200m"
cpu_max = "4"
memory_min = "128Mi"
memory_max = "4Gi"
volume_min = "1Gi"
volume_max = "100Gi"

[[packages]]
name = "hooto-press"
version = "0.10"

# service port
[[service_ports]]
port = 9533
name = "http"

# dependency on postgresql service
[[depends]]
name = "postgresql-v18"

[[tasks]]
name = "install"
run_user = "root"
on_startup = true
script = """
command -v git >/dev/null || apk add --no-cache git
"""

[[tasks]]
name = "run"
depends_on = ["install"]
script = """
if pidof hooto-press; then
    exit 0
fi

mkdir -p /opt/hooto/press/etc
rsync -av ${ipk.hooto_press.path}/* /opt/hooto/press/

/opt/hooto/press/bin/hooto-press >> /home/action/var/log/hooto-press.log 2>&1 &
"""
cron = "*/60 * * * * *"

[[tasks]]
name = "shutdown"
script = "killall hooto-press"
on_shutdown = true

[[configs]]
name = "iam_auth_app_id"
title = "IAM Auth - App ID"
type = "string"

[[configs]]
name = "iam_auth_secret_key"
title = "IAM Auth - Secret Key"
type = "string"

[[configs]]
name = "iam_auth_base_url"
title = "IAM Auth - Base URL"
type = "string"

[[configs]]
name = "database_name"
title = "Database Name"
type = "string"

