[project]
name = "hooto-press-search"
version = "1.0.0"
vendor = "hooto.com"
homepage = "https://github.com/hooto/hpress"
groups = ["app/other"]

[files]
allow = """
misc/sphinxsearch"""

[scripts]
build = """

mkdir -p {{.buildroot}}/bin
mkdir -p {{.buildroot}}/var/{sphinxsearch}

cd {{.inpack__pack_dir}}/deps/sphinxsearch

./configure --prefix=/opt/hooto/press --without-mysql --without-pgsql --with-libexpat
make -j4

install src/indexer   {{.buildroot}}/bin/sph-indexer
install src/indextool {{.buildroot}}/bin/sph-indextool
install src/searchd   {{.buildroot}}/bin/sph-searchd

strip -s {{.buildroot}}/bin/sph-indexer
strip -s {{.buildroot}}/bin/sph-indextool
strip -s {{.buildroot}}/bin/sph-searchd
"""
