[project]
name = "hooto-press"
version = "0.9.0"
vendor = "hooto.com"
homepage = "https://github.com/hooto/hpress"
groups = ["app/other"]

[files]
allow = """
bin/hooto-press
bin/keeper
etc/config.json.tpl
i18n/
modules/core/
websrv/mgr/views/
webui/hpm/
webui/hp/img/alpha2.png
webui/hp/img/search-16.png
webui/hp/img/ap.ico
webui/katex/
"""

js_compress = """
webui/cm/5/
webui/lessui/js/lessui.js
webui/lessui/js/browser-detect.js
webui/lessui/js/eventproxy.js
webui/lessui/js/sea.js
webui/hp/js/
webui/hpm/js/
webui/katex/
modules/core/"""

css_compress = """
webui/cm/5/
webui/lessui/css/lessui.css
webui/lessui/css/base.css
webui/hp/css/
webui/hpm/css/
webui/katex/
modules/core/"""

html_compress_disable = """
modules/core/
webui/hpm/
websrv/mgr/views/"""

png_compress = """
webui/hp/img/
webui/hpm/img/"""

[scripts]
build = """

mkdir -p {{.buildroot}}/bin
mkdir -p {{.buildroot}}/var/{log,storage,tmp}

CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags \"-s -w -X main.version={{.project__version}} -X main.release={{.project__release}}\" -o {{.buildroot}}/bin/hooto-press cmd/server/main.go
# go build -ldflags \"-s -w -X main.version={{.project__version}} -X main.release={{.project__release}}\" -o {{.buildroot}}/bin/hp-s2-upgrade misc/s2-upgrade.go

#sed -i 's/debug:\\!0/debug:\\!1/g' {{.buildroot}}/webui/hp/js/main.js
#sed -i 's/debug:\\!0/debug:\\!1/g' {{.buildroot}}/webui/hpm/js/main.js
#sed -i 's/debug:true/debug:false/g' {{.buildroot}}/webui/hp/js/main.js
#sed -i 's/debug:true/debug:false/g' {{.buildroot}}/webui/hpm/js/main.js

"""
